name: test-build
on:
  repository_dispatch: 
    types: test-build
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - generic/ubuntu1804
          - generic/debian10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Vagrant 
        shell: bash
        run: |
          curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
          curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_SHA256SUMS
          curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_SHA256SUMS.sig
          gpg --receive-key 51852D87348FFC4C
          gpg --verify vagrant_2.2.14_SHA256SUMS.sig vagrant_2.2.14_SHA256SUMS
          sha256sum -c vagrant_2.2.14_SHA256SUMS 2>&1 | grep OK
          sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
          sudo dpkg -i vagrant_2.2.14_x86_64.deb
          sudo vagrant plugin install vagrant-libvirt
          rm -rf vagrant_2.2.14_*
      - name: Install python dependencies 
        shell: bash
        run: |
          sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
          sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
          curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
          sudo -H pip3 install --upgrade --ignore-installed --requirement requirements.txt
      - name: Run Molecule tests.
        run: |
          sudo -E molecule syntax \
          && sudo -E molecule lint \
          && sudo -E molecule create \
          && sudo -E molecule converge \
          && sudo -E molecule verify \
          && sudo -E molecule destroy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
